sudo: required
services:
  - docker

before_install:
  - docker build -t jeanlucami/docker-react -f Dockerfile.dev .

script:
  - docker run jeanlucami/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: jl_docker_react 
  env: "JlDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-245472546622"
  bucket_path: 'jl_docker_react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
